dist: xenial
language: python

python:
  - '3.7'

script: make build

deploy:
  provider: pypi
  user: lifeofguenter
  password:
    secure: CWKL1pcpu4lcJd8+DcE7xqqjRgGt9TMC6OVCRayU8uUHhUYy0INE43K1uRc2W9wSrw9Cf55wxlWNL11SkCeNalroG/OBiiYm3peeJ4mvClyh838UjEZSfWiuQMwldKXjp3u8vBwPOJZRJmGjU4mNLjMKP0aCteOrQiHn9Il3SmNti9ghaVSs2kkc2Be+vb2UOFAt2ovpcB5bJBBBs0g2c4IOw1sWxxvOqilZA+Zw/oXhQwzo1NEOqcWzKuhzsxYlku7UMLvZsYZiMt0w6mnqpNStbgsUrwxXSqnFphs/CeWRYxLVkSjsDBjciEsuC7EuJUtcsVizFMACwHP/EOpKXU8YWXUPGP9LHcSJhcCuk7L/iAC7faJkKB3E+w+h/IyeL5zbSJxA4KrJNro3ItJ4sugkMLEBjAcHqmA64FUulcqE0H+KTRb1KW7bLF2a6qZ/yRk1tsUGBMF8nBrjvW6BFd8wLnbOG2dnErfeF7JL0VjaKqRLFfj8fujR9hJ3vt/Jnkf8N8wrMIYHz1+sVuT+Kzg1d/53voi6KWRQFR/dRh3u58w//PfZJSG6zvpXwQx2HvS8OsiZMfRsKdSGWVyfM1NoNhxzVs2Q3nee612GnYMnnp1JKOb5MbfuhbM+/FifjJ0/WAnisAT0Rz3DgyZtVoGayLvt2b0V4kb1pLdLD0Q=
  on:
    tags: true
